---

info:
  description: Training configuration repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://sam:michels@eureka-smichels.cfapps.io/eureka

---
spring:
  profiles: local
eureka:
  instance:
    hostname: http://sam:michels@eureka-smichels.cfapps.io/eureka
    nonSecurePort: 80