---

info:
  description: Training configuration repo

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.application.application_uris[0]} # http://sam:michels@eureka-smichels.cfapps.io/eureka

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: https://company-smichels.cfapps.io
    nonSecurePort: 80